# Identidad del proyecto en SonarQube Cloud (valores de TU cuenta)
sonar.organization=hutsebautvictor-star
sonar.projectKey=hutsebautvictor-star_reportaudit-lab
sonar.projectName=ReportAudit

# Qué se analiza y cómo
sonar.sources=app
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

# Cobertura producida por las pruebas de regresión en GitHub Actions
sonar.python.coverage.reportPaths=coverage.xml
